"""Initial schema

Revision ID: a47d20e368a5
Revises: 
Create Date: 2026-04-02 14:07:18.785978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a47d20e368a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('forgot_password_verifications', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('forgot_password_verifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('forgot_password_verifications', 'otp_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('forgot_password_verifications', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_forgot_pw_user_id'), table_name='forgot_password_verifications')
    op.create_index(op.f('ix_forgot_password_verifications_id'), 'forgot_password_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_forgot_password_verifications_user_id'), 'forgot_password_verifications', ['user_id'], unique=False)
    op.create_foreign_key(None, 'forgot_password_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'login_verifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('platform_activity', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('platform_activity', 'action_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('platform_activity', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('platform_activity', 'extra_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_platform_activity_id'), 'platform_activity', ['id'], unique=False)
    op.alter_column('signup_verifications', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('signup_verifications', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('signup_verifications', 'mobile',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'email_otp_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'mobile_otp_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_signup_verifications_email'), 'signup_verifications', ['email'], unique=True)
    op.create_index(op.f('ix_signup_verifications_id'), 'signup_verifications', ['id'], unique=False)
    op.drop_column('signup_verifications', 'email_otp')
    op.drop_column('signup_verifications', 'mobile_otp')
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('signup_verifications', sa.Column('mobile_otp', sa.TEXT(), nullable=True))
    op.add_column('signup_verifications', sa.Column('email_otp', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_signup_verifications_id'), table_name='signup_verifications')
    op.drop_index(op.f('ix_signup_verifications_email'), table_name='signup_verifications')
    op.alter_column('signup_verifications', 'mobile_otp_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'email_otp_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'mobile',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('signup_verifications', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('signup_verifications', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_platform_activity_id'), table_name='platform_activity')
    op.alter_column('platform_activity', 'extra_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('platform_activity', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('platform_activity', 'action_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('platform_activity', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'login_verifications', type_='foreignkey')
    op.drop_constraint(None, 'forgot_password_verifications', type_='foreignkey')
    op.drop_index(op.f('ix_forgot_password_verifications_user_id'), table_name='forgot_password_verifications')
    op.drop_index(op.f('ix_forgot_password_verifications_id'), table_name='forgot_password_verifications')
    op.create_index(op.f('ix_forgot_pw_user_id'), 'forgot_password_verifications', ['user_id'], unique=False)
    op.alter_column('forgot_password_verifications', 'expires_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('forgot_password_verifications', 'otp_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('forgot_password_verifications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('forgot_password_verifications', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
