"""Add SaaS platform tables for B2B support

Revision ID: b9d3c4b1ade6
Revises: a47d20e368a5
Create Date: 2026-04-27 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9d3c4b1ade6'
down_revision: Union[str, None] = 'a47d20e368a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. organizations table (B2B support)
    op.create_table('organizations',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the organization'),
        sa.Column('name', sa.String(255), nullable=False, comment='Display name of the organization'),
        sa.Column('slug', sa.String(100), nullable=False, unique=True, comment='URL-friendly identifier for the organization'),
        sa.Column('plan', sa.Enum('free', 'starter', 'pro', 'enterprise', name='organization_plan'), nullable=False, comment='Current subscription plan tier'),
        sa.Column('monthly_cost', sa.Integer(), nullable=False, comment='Monthly cost in cents'),
        sa.Column('api_calls_limit', sa.Integer(), nullable=False, comment='Monthly API calls limit'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when organization was created'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when organization was last updated'),
        sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp'),
        comment='Organizations table for B2B multi-tenancy support'
    )

    # 2. subscriptions table (Stripe integration)
    op.create_table('subscriptions',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the subscription'),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, comment='Reference to the organization'),
        sa.Column('stripe_subscription_id', sa.String(), nullable=False, unique=True, comment='Stripe subscription ID'),
        sa.Column('stripe_customer_id', sa.String(), nullable=False, unique=True, comment='Stripe customer ID'),
        sa.Column('tier', sa.Enum('free', 'starter', 'pro', 'enterprise', name='subscription_tier'), nullable=False, comment='Subscription tier'),
        sa.Column('monthly_cost', sa.Integer(), nullable=False, comment='Monthly cost in cents'),
        sa.Column('next_billing_date', sa.DateTime(), nullable=False, comment='Next billing date'),
        sa.Column('status', sa.Enum('active', 'past_due', 'canceled', 'trialing', name='subscription_status'), nullable=False, comment='Subscription status'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when subscription was created'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when subscription was last updated'),
        comment='Subscriptions table for Stripe billing integration'
    )

    # 3. api_keys table (Programmatic access)
    op.create_table('api_keys',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the API key'),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, comment='Reference to the organization'),
        sa.Column('name', sa.String(100), nullable=False, comment='Display name for the API key'),
        sa.Column('key_prefix', sa.String(8), nullable=False, comment='First 8 characters of the API key for display'),
        sa.Column('key_hash', sa.String(255), nullable=False, comment='Bcrypt hash of the full API key'),
        sa.Column('scopes', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='JSON array of scopes (e.g., ["read:projects", "write:projects"])'),
        sa.Column('rate_limit', sa.Integer(), nullable=False, comment='Rate limit in requests per minute'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when API key was created'),
        sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Expiration timestamp for the API key'),
        sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Timestamp when API key was last used'),
        sa.Column('active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the API key is active'),
        comment='API keys table for programmatic access'
    )

    # 4. usage table (Metered billing)
    op.create_table('usage',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the usage record'),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, comment='Reference to the organization'),
        sa.Column('api_calls', sa.Integer(), server_default='0', nullable=False, comment='Number of API calls made'),
        sa.Column('documents_generated', sa.Integer(), server_default='0', nullable=False, comment='Number of documents generated'),
        sa.Column('pages_processed', sa.Integer(), server_default='0', nullable=False, comment='Number of pages processed'),
        sa.Column('storage_mb', sa.Integer(), server_default='0', nullable=False, comment='Storage used in MB'),
        sa.Column('period_start', sa.Date(), nullable=False, comment='Start date of the billing period'),
        sa.Column('period_end', sa.Date(), nullable=False, comment='End date of the billing period'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when usage record was created'),
        comment='Usage table for metered billing tracking'
    )

    # 5. audit_logs table (Compliance)
    op.create_table('audit_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the audit log entry'),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, comment='Reference to the organization'),
        sa.Column('actor_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False, comment='Reference to the user who performed the action'),
        sa.Column('action', sa.String(), nullable=False, comment='Action performed (e.g., "project_created", "api_key_created")'),
        sa.Column('resource_type', sa.String(), nullable=False, comment='Type of resource affected (e.g., "project", "user")'),
        sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=False, comment='ID of the affected resource'),
        sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='JSON object describing what changed'),
        sa.Column('ip_address', sa.String(), nullable=False, comment='IP address of the actor'),
        sa.Column('user_agent', sa.String(), nullable=False, comment='User agent string'),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when the action occurred'),
        sa.Column('status', sa.Enum('success', 'failure', name='audit_status'), nullable=False, comment='Status of the action (success or failure)'),
        comment='Audit logs table for compliance and security tracking'
    )

    # 6. templates table (Custom templates)
    op.create_table('templates',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the template'),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=True, comment='Reference to the organization (NULL for public templates)'),
        sa.Column('name', sa.String(255), nullable=False, comment='Display name of the template'),
        sa.Column('category', sa.String(50), nullable=False, comment='Category of the template'),
        sa.Column('description', sa.Text(), nullable=False, comment='Description of the template'),
        sa.Column('content', sa.Text(), nullable=False, comment='Template structure/content'),
        sa.Column('variables', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='JSON array of required variables'),
        sa.Column('is_public', sa.Boolean(), nullable=False, comment='Whether the template is publicly available'),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=False, comment='Reference to the user who created the template'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when template was created'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when template was last updated'),
        comment='Templates table for custom document templates'
    )

    # 7. webhooks table (Event delivery)
    op.create_table('webhooks',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the webhook'),
        sa.Column('organization_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('organizations.id', ondelete='CASCADE'), nullable=False, comment='Reference to the organization'),
        sa.Column('url', sa.String(), nullable=False, comment='Webhook endpoint URL'),
        sa.Column('events', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='JSON array of events to listen for'),
        sa.Column('secret', sa.String(), nullable=False, comment='HMAC secret for webhook validation'),
        sa.Column('active', sa.Boolean(), server_default='true', nullable=False, comment='Whether the webhook is active'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when webhook was created'),
        sa.Column('created_by', sa.Integer(), sa.ForeignKey('users.id'), nullable=False, comment='Reference to the user who created the webhook'),
        comment='Webhooks table for event delivery'
    )

    # 8. webhook_deliveries table (Retry tracking)
    op.create_table('webhook_deliveries',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('gen_random_uuid()'), comment='Unique identifier for the webhook delivery attempt'),
        sa.Column('webhook_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('webhooks.id', ondelete='CASCADE'), nullable=False, comment='Reference to the webhook'),
        sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False, comment='JSON payload sent to the webhook'),
        sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP status code from the webhook endpoint'),
        sa.Column('response', sa.Text(), nullable=True, comment='Response body from the webhook endpoint'),
        sa.Column('attempts', sa.Integer(), server_default='1', nullable=False, comment='Number of delivery attempts made'),
        sa.Column('next_retry', sa.DateTime(), nullable=True, comment='Timestamp for next retry attempt'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Timestamp when delivery attempt was made'),
        comment='Webhook deliveries table for retry tracking'
    )

    # Create indexes as specified
    op.create_index('ix_organizations_id', 'organizations', ['id'], unique=False)
    op.create_index('ix_organizations_created_at', 'organizations', ['created_at'], unique=False)

    op.create_index('ix_subscriptions_organization_id', 'subscriptions', ['organization_id'], unique=False)
    op.create_index('ix_subscriptions_stripe_subscription_id', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index('ix_subscriptions_created_at', 'subscriptions', ['created_at'], unique=False)

    op.create_index('ix_api_keys_organization_id', 'api_keys', ['organization_id'], unique=False)
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('ix_api_keys_created_at', 'api_keys', ['created_at'], unique=False)

    op.create_index('ix_usage_organization_id', 'usage', ['organization_id'], unique=False)
    op.create_index('ix_usage_period_start', 'usage', ['period_start'], unique=False)
    op.create_index('ix_usage_created_at', 'usage', ['created_at'], unique=False)

    op.create_index('ix_audit_logs_organization_id', 'audit_logs', ['organization_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)

    op.create_index('ix_templates_organization_id', 'templates', ['organization_id'], unique=False)
    op.create_index('ix_templates_created_at', 'templates', ['created_at'], unique=False)

    op.create_index('ix_webhooks_organization_id', 'webhooks', ['organization_id'], unique=False)
    op.create_index('ix_webhooks_created_at', 'webhooks', ['created_at'], unique=False)

    op.create_index('ix_webhook_deliveries_webhook_id', 'webhook_deliveries', ['webhook_id'], unique=False)
    op.create_index('ix_webhook_deliveries_created_at', 'webhook_deliveries', ['created_at'], unique=False)

    # Add CHECK constraints for enum fields
    op.create_check_constraint('organizations_plan_check', 'organizations', "plan IN ('free', 'starter', 'pro', 'enterprise')")
    op.create_check_constraint('subscriptions_tier_check', 'subscriptions', "tier IN ('free', 'starter', 'pro', 'enterprise')")
    op.create_check_constraint('subscriptions_status_check', 'subscriptions', "status IN ('active', 'past_due', 'canceled', 'trialing')")
    op.create_check_constraint('audit_logs_status_check', 'audit_logs', "status IN ('success', 'failure')")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop CHECK constraints
    op.drop_constraint('audit_logs_status_check', 'audit_logs', type_='check')
    op.drop_constraint('subscriptions_status_check', 'subscriptions', type_='check')
    op.drop_constraint('subscriptions_tier_check', 'subscriptions', type_='check')
    op.drop_constraint('organizations_plan_check', 'organizations', type_='check')

    # Drop indexes
    op.drop_index('ix_webhook_deliveries_created_at', table_name='webhook_deliveries')
    op.drop_index('ix_webhook_deliveries_webhook_id', table_name='webhook_deliveries')
    op.drop_index('ix_webhooks_created_at', table_name='webhooks')
    op.drop_index('ix_webhooks_organization_id', table_name='webhooks')
    op.drop_index('ix_templates_created_at', table_name='templates')
    op.drop_index('ix_templates_organization_id', table_name='templates')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_organization_id', table_name='audit_logs')
    op.drop_index('ix_usage_created_at', table_name='usage')
    op.drop_index('ix_usage_period_start', table_name='usage')
    op.drop_index('ix_usage_organization_id', table_name='usage')
    op.drop_index('ix_api_keys_created_at', table_name='api_keys')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_index('ix_api_keys_organization_id', table_name='api_keys')
    op.drop_index('ix_subscriptions_created_at', table_name='subscriptions')
    op.drop_index('ix_subscriptions_stripe_subscription_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_organization_id', table_name='subscriptions')
    op.drop_index('ix_organizations_created_at', table_name='organizations')
    op.drop_index('ix_organizations_id', table_name='organizations')

    # Drop tables
    op.drop_table('webhook_deliveries')
    op.drop_table('webhooks')
    op.drop_table('templates')
    op.drop_table('audit_logs')
    op.drop_table('usage')
    op.drop_table('api_keys')
    op.drop_table('subscriptions')
    op.drop_table('organizations')

    # ### end Alembic commands ###